# -*- coding: utf-8 -*-
"""python 3rd project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VGggNwwS4JBqa0nbe0be_--6AextLv_6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('Youth_Tobacco.csv')
df

df.head()

df.info()

df.drop('Data_Value_Footnote_Symbol',axis=1,inplace=True)

df.drop('Data_Value_Footnote',axis=1,inplace=True)

df.info()

"""Question 1: How has tabacco consumption varied between the years 1999-2017?"""

# Filter data for Youth Cigarette Use (Ever)
filtered_df = df[(df["TopicDesc"] == "Cigarette Use (Youth)") &(df["Response"] == "Ever")]

# Group by year and calculate average tobacco consumption
yearly_trend = filtered_df.groupby("YEAR")["Data_Value"].mean().reset_index()

# Plot the trend
plt.figure()
plt.plot(yearly_trend["YEAR"], yearly_trend["Data_Value"])
plt.xlabel("Year")
plt.ylabel("Average Tobacco Consumption (%)")
plt.title("Youth Tobacco Consumption Trend (1999–2017)")
plt.show()

# Display first and last few records
print(yearly_trend.head())
print(yearly_trend.tail())

"""Question 2: How has tobacco consumption differed between genders?"""

# Filter for Youth Cigarette Use (Ever) and gender-wise data
gender_df = df[
    (df["TopicDesc"] == "Cigarette Use (Youth)") &
    (df["Response"] == "Ever") &
    (df["Gender"].isin(["Male", "Female"]))
]

# Calculate average tobacco consumption by gender
gender_avg = gender_df.groupby("Gender")["Data_Value"].mean().reset_index()

# Plot comparison
plt.figure()
plt.bar(gender_avg["Gender"], gender_avg["Data_Value"])
plt.xlabel("Gender")
plt.ylabel("Average Tobacco Consumption (%)")
plt.title("Youth Tobacco Consumption by Gender")
plt.show()

print(gender_avg)

# Filter for Youth Smokeless Tobacco Use (Ever) and gender-wise data
gender_df = df[
    (df["TopicDesc"] == "Smokeless Tobacco Use (Youth)") &
    (df["Response"] == "Ever") &
    (df["Gender"].isin(["Male", "Female"]))]

# Calculate average tobacco consumption by gender
gender_avg = gender_df.groupby("Gender")["Data_Value"].mean().reset_index()

# Plot comparison
plt.figure()
plt.bar(gender_avg["Gender"], gender_avg["Data_Value"])
plt.xlabel("Gender")
plt.ylabel("Average Tobacco Consumption (%)")
plt.title("Youth Tobacco Consumption by Gender")
plt.show()

print(gender_avg)

"""Question 3: What states in America have the highest percentage of students consuming tobacco"""

# Filter data for youth cigarette use (Ever)
state_df = df[
    (df["TopicDesc"] == "Cigarette Use (Youth)") &
    (df["Response"] == "Ever") &
    (df["LocationDesc"] != "United States")
]

# Calculate average tobacco consumption by state
state_avg = state_df.groupby("LocationDesc")["Data_Value"].mean().reset_index()

# Select top 5 states with highest consumption
top_states = state_avg.sort_values(by="Data_Value", ascending=False).head(5)

# Plot pie chart
plt.figure()
plt.pie(
    top_states["Data_Value"],
    labels=top_states["LocationDesc"],
    autopct="%1.1f%%"
)
plt.title("Top 5 U.S. States with Highest Youth Tobacco Consumption")
plt.show()